import { Role } from '../types/enums';

export const Permission = {
  VIEW_TEAM: 'VIEW_TEAM',
  MANAGE_TEAM: 'MANAGE_TEAM',
  MANAGE_ORGANIZATION: 'MANAGE_ORGANIZATION',
  MANAGE_MEMBERS: 'MANAGE_MEMBERS',
  MANAGE_PLAYERS: 'MANAGE_PLAYERS',
  VIEW_SENSITIVE_PLAYER: 'VIEW_SENSITIVE_PLAYER',
  MANAGE_SENSITIVE_PLAYER: 'MANAGE_SENSITIVE_PLAYER',
  MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',
  MANAGE_DEVELOPMENT: 'MANAGE_DEVELOPMENT',
  MANAGE_EVENTS: 'MANAGE_EVENTS',
  MANAGE_LINEUPS: 'MANAGE_LINEUPS',
  MANAGE_LIVE_TICKER: 'MANAGE_LIVE_TICKER',
  VIEW_PLAYER_STATS: 'VIEW_PLAYER_STATS',
  MANAGE_STATISTICS: 'MANAGE_STATISTICS',
  MANAGE_TRAINING: 'MANAGE_TRAINING',
  SEND_ANNOUNCEMENTS: 'SEND_ANNOUNCEMENTS',
  MANAGE_IMPORTS: 'MANAGE_IMPORTS',
  RESPOND_ATTENDANCE: 'RESPOND_ATTENDANCE',
  VIEW_TEAM_OPERATIONS: 'VIEW_TEAM_OPERATIONS',
  MANAGE_TEAM_OPERATIONS: 'MANAGE_TEAM_OPERATIONS',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

const allPermissions = Object.values(Permission);

const permissionsByRole: Record<Role, readonly Permission[]> = {
  [Role.SUPER_ADMIN]: allPermissions,
  [Role.CLUB_ADMIN]: allPermissions,
  [Role.TRAINER_ADMIN]: allPermissions,
  [Role.YOUTH_DIRECTOR]: allPermissions,
  [Role.COACH]: [
    Permission.VIEW_TEAM,
    Permission.MANAGE_TEAM,
    Permission.MANAGE_MEMBERS,
    Permission.MANAGE_PLAYERS,
    Permission.VIEW_SENSITIVE_PLAYER,
    Permission.MANAGE_SENSITIVE_PLAYER,
    Permission.MANAGE_DOCUMENTS,
    Permission.MANAGE_DEVELOPMENT,
    Permission.MANAGE_EVENTS,
    Permission.MANAGE_LINEUPS,
    Permission.MANAGE_LIVE_TICKER,
    Permission.VIEW_PLAYER_STATS,
    Permission.MANAGE_STATISTICS,
    Permission.MANAGE_TRAINING,
    Permission.SEND_ANNOUNCEMENTS,
    Permission.MANAGE_IMPORTS,
    Permission.RESPOND_ATTENDANCE,
    Permission.VIEW_TEAM_OPERATIONS,
    Permission.MANAGE_TEAM_OPERATIONS,
  ],
  [Role.TRAINER]: [
    Permission.VIEW_TEAM,
    Permission.MANAGE_TEAM,
    Permission.MANAGE_MEMBERS,
    Permission.MANAGE_PLAYERS,
    Permission.VIEW_SENSITIVE_PLAYER,
    Permission.MANAGE_SENSITIVE_PLAYER,
    Permission.MANAGE_DOCUMENTS,
    Permission.MANAGE_DEVELOPMENT,
    Permission.MANAGE_EVENTS,
    Permission.MANAGE_LINEUPS,
    Permission.MANAGE_LIVE_TICKER,
    Permission.VIEW_PLAYER_STATS,
    Permission.MANAGE_STATISTICS,
    Permission.MANAGE_TRAINING,
    Permission.SEND_ANNOUNCEMENTS,
    Permission.MANAGE_IMPORTS,
    Permission.RESPOND_ATTENDANCE,
    Permission.VIEW_TEAM_OPERATIONS,
    Permission.MANAGE_TEAM_OPERATIONS,
  ],
  [Role.ASSISTANT_COACH]: [
    Permission.VIEW_TEAM,
    Permission.MANAGE_PLAYERS,
    Permission.VIEW_SENSITIVE_PLAYER,
    Permission.MANAGE_DOCUMENTS,
    Permission.MANAGE_DEVELOPMENT,
    Permission.MANAGE_EVENTS,
    Permission.MANAGE_LINEUPS,
    Permission.MANAGE_LIVE_TICKER,
    Permission.VIEW_PLAYER_STATS,
    Permission.MANAGE_STATISTICS,
    Permission.MANAGE_TRAINING,
    Permission.SEND_ANNOUNCEMENTS,
    Permission.MANAGE_IMPORTS,
    Permission.RESPOND_ATTENDANCE,
    Permission.VIEW_TEAM_OPERATIONS,
    Permission.MANAGE_TEAM_OPERATIONS,
  ],
  [Role.TEAM_MANAGER]: [
    Permission.VIEW_TEAM,
    Permission.MANAGE_MEMBERS,
    Permission.MANAGE_PLAYERS,
    Permission.VIEW_SENSITIVE_PLAYER,
    Permission.MANAGE_EVENTS,
    Permission.MANAGE_LINEUPS,
    Permission.MANAGE_LIVE_TICKER,
    Permission.VIEW_PLAYER_STATS,
    Permission.MANAGE_STATISTICS,
    Permission.MANAGE_TRAINING,
    Permission.SEND_ANNOUNCEMENTS,
    Permission.MANAGE_IMPORTS,
    Permission.RESPOND_ATTENDANCE,
    Permission.VIEW_TEAM_OPERATIONS,
    Permission.MANAGE_TEAM_OPERATIONS,
  ],
  [Role.PARENT]: [
    Permission.VIEW_TEAM,
    Permission.VIEW_PLAYER_STATS,
    Permission.RESPOND_ATTENDANCE,
    Permission.VIEW_TEAM_OPERATIONS,
  ],
  [Role.PLAYER]: [
    Permission.VIEW_TEAM,
    Permission.VIEW_PLAYER_STATS,
    Permission.RESPOND_ATTENDANCE,
    Permission.VIEW_TEAM_OPERATIONS,
  ],
  [Role.READ_ONLY]: [Permission.VIEW_TEAM, Permission.VIEW_TEAM_OPERATIONS],
};

export function hasPermission(role: Role, permission: Permission) {
  return permissionsByRole[role]?.includes(permission) ?? false;
}

export function permissionsForRole(role: Role) {
  return [...(permissionsByRole[role] ?? [])];
}
