import { asyncRouter } from '../middleware/async-handler';
import { requireAuth, requireApproved } from '../middleware/auth';
import { sensitiveActionRateLimit } from '../middleware/rate-limit';
import * as absences from '../controllers/absences.controller';
import * as polls from '../controllers/polls.controller';
import * as goals from '../controllers/goals.controller';
import * as invitations from '../controllers/invitations.controller';
import { talentsOptions } from '../controllers/talents-options.controller';
import { assistantTasks } from '../controllers/talents-assistant.controller';
import { matchdayReadiness, createMatchdayChecklist, printReport } from '../controllers/talents-matchday.controller';

const router = asyncRouter();
router.get('/invitation-preview', sensitiveActionRateLimit, invitations.previewInvitation);
router.use(requireAuth);
router.post('/invitations/claim', invitations.claimInvitation);
router.use(requireApproved);
router.get('/options', talentsOptions);
router.get('/assistant', assistantTasks);
router.get('/matches/:id/readiness', matchdayReadiness);
router.post('/matches/:id/checklist', createMatchdayChecklist);
router.post('/reports/print', sensitiveActionRateLimit, printReport);
router.get('/absences', absences.listAbsences);
router.post('/absences', absences.saveAbsence);
router.put('/absences/:id', absences.saveAbsence);
router.post('/absences/:id/end', absences.endAbsence);
router.get('/polls', polls.listPolls);
router.post('/polls', polls.createPoll);
router.put('/polls/:id/vote', polls.votePoll);
router.post('/polls/:id/manage', polls.managePoll);
router.get('/goals', goals.listGoals);
router.get('/goals/:id/development', goals.getGoalDevelopment);
router.post('/goals', goals.saveGoal);
router.put('/goals/:id', goals.saveGoal);
router.post('/goals/:id/observations', goals.observeGoal);
router.get('/invitations', invitations.listInvitations);
router.post('/invitations', invitations.createInvitation);
router.post('/invitations/:id/revoke', invitations.revokeInvitation);
router.post('/invitations/claims/:id/review', invitations.reviewInvitationClaim);
export default router;
