ALTER TYPE "TeamGameFormat" ADD VALUE IF NOT EXISTS 'FOOTBALL_2';
ALTER TYPE "TeamGameFormat" ADD VALUE IF NOT EXISTS 'FOOTBALL_4_MINI';
ALTER TYPE "TeamGameFormat" ADD VALUE IF NOT EXISTS 'FOOTBALL_6';
ALTER TABLE "MatchDetails" ADD COLUMN "gameFormat" "TeamGameFormat";
